import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/Header";
import ConvexClientProvider from "./ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // bg-linear-to-br from-blue-900 via-indigo-950 to-black
    // bg-linear-to-br from-indigo-900 via-cyan-900 to-gray-950

    <html lang="en">
      <body
        className={`bg-linear-to-br from-purple-900 via-indigo-900 to-slate-950`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <ClerkProvider>
            <ConvexClientProvider>
              <Header />
              <main className="min-h-screen container mx-auto">{children}</main>
            </ConvexClientProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
